# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-18 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('current_weight', models.CharField(max_length=200)),
                ('goal_weight', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('lifestyle', models.CharField(max_length=200)),
                ('hashid', models.CharField(max_length=50)),
            ],
        ),
    ]
