# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-19 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pas', '0003_user_current_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_diet',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal_weight',
            field=models.FloatField(),
        ),
    ]
